import "./globals.css";
import Header from "../components/layout/header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning className="overflow-hidden">
      <head>
        <meta name="grammarly-verification" content="off" />
        <style>
          {`
            ::-webkit-scrollbar {
              display: none;
            }
            * {
              -ms-overflow-style: none;
              scrollbar-width: none;
            }
          `}
        </style>
      </head>
      <body
        className="bg-gray-900 text-gray-100 overflow-hidden"
        suppressHydrationWarning
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
